# Generated by Django 3.1.6 on 2021-05-18 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aaltu', '0007_auto_20210422_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaltu.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaltu.products')),
            ],
        ),
    ]
