# Generated by Django 3.1.6 on 2021-05-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaltu', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank='True', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank='True', default='', max_length=20),
        ),
    ]
